# Generated by Django 3.2 on 2022-09-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogs_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name_plural': 'Blog Page'},
        ),
    ]
