# Generated by Django 3.2 on 2022-10-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
