# Generated by Django 3.2 on 2022-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(blank=True, help_text='If you have your image hosted anywhere else, add the link here to server as a backup.', max_length=254, null=True),
        ),
    ]
