# Generated by Django 3.2 on 2022-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bandcamp_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='soundcloud_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='blog_button',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='shop_button',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
