# Generated by Django 3.2 on 2022-10-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
