# Generated by Django 3.2 on 2022-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text='This name should be all lowercase, and contain no spaces.', max_length=254),
        ),
    ]
