# Generated by Django 3.2 on 2022-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_merch_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='digital_download',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
