# Generated by Django 3.2 on 2022-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_album_digital_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
