# Generated by Django 3.2 on 2022-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_song_track_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
