# Generated by Django 3.2 on 2022-10-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
